#! /bin/bash

set -e

if [ $# -ne 3 ]
  then
    echo "Please provide a bike list url and the bike type (this will be used as a folder) and output folder"
    exit
fi

geckodriver &
cargo run -- $1 $2 $3
